version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.55.2
    working_directory: ~/src
    steps:
      - run: apk update && apk add git
      - add_ssh_keys:
          fingerprints:
            - "${SSH_FINGERPRINT}"
      - checkout
      - run: git submodule update --init
      - run: hugo -v -s ~/src
      - run:
          name: test the generated html files
          command: htmlproofer ~/src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - deploy:
          name: push to master branch
          command: ./deploy.sh
